apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: account-service:1.0
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: 172.21.112.1
          imagePullPolicy: Always
